survey_app/urls.py
from django.conf.urls import url
from . import views

app_name = 'survey_app'
urlpatterns = [

    # ex: /survey_app/
    url(r'^$', views.index, name='index'),

    # ex: /survey_app/
    url(r'^detail/$', views.detail, name='detail'),

    # ex: /survey_app/
    url(r'^submit/', views.submit, name='submit'),

    url(r'^vote/$', views.vote, name='vote'),

]

surveyapp/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^survey_app/', include('survey_app.urls')),
]

survey_app/models.py
from __future__ import unicode_literals

from django.db import models

# Create your models here.


class Ip_addr(models.Model):
    ip_addr = models.CharField(max_length=200)

    def __str__(self):
        return self.ip_addr

class Question(models.Model):
    question_text = models.CharField(max_length=1000)

    def __str__(self):
        return self.question_text

class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return self.choice_text

class Freetext(models.Model):
    free_text = models.CharField(max_length=1000)

    def __str__(self):
        return self.free_text

survey_app/views.py
from django.shortcuts import render
from django.shortcuts import render, get_object_or_404
from .models import Question, Freetext, Ip_addr, Choice
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.views import generic
import sys
reload(sys)
sys.setdefaultencoding('utf8')

# Create your views here.

def get_client_ip(request):
    x_forwarded_for = request.META.get('HTTP_X_FORWARDED_FOR')
    if x_forwarded_for:
        ip = x_forwarded_for.split(',')[0]
    else:
        ip = request.META.get('REMOTE_ADDR')
    return ip

def index(request):
    questions = Question.objects.all()
    context = {'questions': questions}
    return render(request, 'survey_app/index.html', context)

def detail(request):
    ip = get_client_ip(request)

    if Ip_addr.objects.filter(ip_addr=ip).exists():
        return render(request, 'survey_app/exist.html')

    else:



        questions = Question.objects.get(pk=1)
        questions2 = Question.objects.get(pk=2)
        questions3 = Question.objects.get(pk=3)
        questions4 = Question.objects.get(pk=4)
        questions5 = Question.objects.get(pk=5)
        #radio_checker = False
        context = {'questions': questions,
                   'questions2': questions2,
                   'questions3': questions3,
                   'questions4': questions4,
                   'questions5': questions5,
                   'ip': ip,
                   #'radio_checker': radio_checker
                   }
        return render(request, 'survey_app/detail.html', context)

def submit(request):
    questions = Question.objects.all()
    context = {'questions': questions}
    return render(request, 'survey_app/submit.html', context)

'''
def vote(request):
    #question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = Choice.objects.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        # Redisplay the question voting form.
        return render(request, 'survey_app/detail.html', {

            'error_message': "You didn't select a choice.",
        })
    else:
        selected_choice.votes += 1
        selected_choice.save()
        # Always return an HttpResponseRedirect after successfully dealing
        # with POST data. This prevents data from being posted twice if a
        # user hits the Back button.
        return HttpResponseRedirect(reverse('survey_app:submit'))
'''

def vote(request):
    if request.method == 'POST':
        questions = Question.objects.get(pk=1)
        questions2 = Question.objects.get(pk=2)
        questions3 = Question.objects.get(pk=3)
        questions4 = Question.objects.get(pk=4)
        questions5 = Question.objects.get(pk=5)
        radio_checker1 = False
        radio_checker2 = False
        radio_checker3 = False
        radio_checker4 = False
        radio_checker5 = False
        context_checker = ''
        ip = get_client_ip(request)

        try:
            selected_choice = Choice.objects.get(pk=request.POST['question1'])
            radio_checker1 = selected_choice.choice_text


            selected_choice2 = Choice.objects.get(pk=request.POST['question2'])
            radio_checker2 = selected_choice2.choice_text


            selected_choice3 = Choice.objects.get(pk=request.POST['question3'])
            radio_checker3 = selected_choice3.choice_text

            selected_choice4 = Choice.objects.get(pk=request.POST['question4'])
            radio_checker4 = selected_choice4.choice_text

            content = request.POST["content"]



        except (KeyError, Choice.DoesNotExist, ):

            if 'question2' in request.POST:
                selected_choice2 = Choice.objects.get(pk=request.POST['question2'])
                radio_checker2 = selected_choice2.choice_text
            else:
                pass

            if 'question3' in request.POST:
                selected_choice3 = Choice.objects.get(pk=request.POST['question3'])
                radio_checker3 = selected_choice3.choice_text
            else:
                pass

            if 'question4' in request.POST:
                selected_choice4 = Choice.objects.get(pk=request.POST['question4'])
                radio_checker4 = selected_choice4.choice_text
            else:
                pass

            if 'content' in request.POST:
                content_checker = request.POST["content"]
            else:
                pass

            return render(request, 'survey_app/detail.html', {
            'questions': questions,
            'questions2': questions2,
            'questions3': questions3,
            'questions4': questions4,
            'questions5': questions5,
            'radio_checker1': radio_checker1,
            'radio_checker2': radio_checker2,
            'radio_checker3': radio_checker3,
            'radio_checker4': radio_checker4,
            'content_checker': content_checker,
            'error_message': "You didn't select a choice.",
            })
        else:
            if Ip_addr.objects.filter(ip_addr=ip).exists():
                return render(request, 'survey_app/exist.html')

            else:
                selected_choice.votes += 1
                selected_choice.save()
                selected_choice2.votes += 1
                selected_choice2.save()
                selected_choice3.votes += 1
                selected_choice3.save()
                selected_choice4.votes += 1
                selected_choice4.save()

                content = request.POST["content"]
                a = Freetext(free_text=content)
                a.save()
                reg_ip = Ip_addr.objects.create(ip_addr=ip)
                reg_ip.save()

                return HttpResponseRedirect(reverse('survey_app:submit'))

survey_app/templates/survey_app/detail.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <title>Web Services Survey</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" >
  <script src="{% static 'jquery/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>

{{ ip }}

<div class="container">
{% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}


<form action="{% url 'survey_app:vote' %}" method="post">{% csrf_token %}

    <h3>1. {{ questions.question_text }}</h3>

        {% csrf_token %}
        {% for choice in questions.choice_set.all %}
        <input type="radio" name="question1" id="choice{{ forloop.counter }}" value="{{ choice.id }}" {% if  choice.choice_text   == radio_checker1 %}checked="checked"{% endif %}/>
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
        {% endfor %}

    <h3>2. {{ questions2.question_text }}</h3>
        {% csrf_token %}
        {% for choice in questions2.choice_set.all %}
        <input type="radio" name="question2" id="choice{{ forloop.counter }}" value="{{ choice.id }}" {% if  choice.choice_text  == radio_checker2 %}checked="checked"{% endif %}/>
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
        {% endfor %}


    <h3>3. {{ questions3.question_text }}</h3>
        {% csrf_token %}
        {% for choice in questions3.choice_set.all %}
        <input type="radio" name="question3" id="choice{{ forloop.counter }}" value="{{ choice.id }}" {% if  choice.choice_text  == radio_checker3 %}checked="checked"{% endif %}/>
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
        {% endfor %}

    <h3>4. {{ questions4.question_text }}</h3>
        {% csrf_token %}
        {% for choice in questions4.choice_set.all %}
        <input type="radio" name="question4" id="choice{{ forloop.counter }}" value="{{ choice.id }}" {% if  choice.choice_text  == radio_checker4 %}checked="checked"{% endif %}/>
            <label for="choice{{ forloop.counter }}">{{ choice.choice_text }}</label><br />
        {% endfor %}


    <h3>5. {{ questions5.question_text }}</h3>

    <textarea name="content" rows="10" cols="100">{{ content_checker }}</textarea><br>



<input type="submit" value="Submit" />
</form>


    </div>

survey_app/templates/survey_app/exist.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Web Services Survey</title>
</head>
<body>
<h3>Oops, you've already submitted the survey</h3>
</body>
</html>

survey_app/templates/survey_app/index.html
<!DOCTYPE html>
{% load static %}
<html lang="en">
<head>
  <title>Web Services Survey</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" >
  <script src="{% static 'jquery/jquery.min.js' %}"></script>
    <script src="{% static 'js/bootstrap.min.js' %}"></script>
</head>
<body>

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>
<h1>This is an index page</h1>
<div class="container">
  <h2>Button Styles</h2>
  <button type="button" class="btn btn-default">Default</button>
  <button type="button" class="btn btn-primary">Primary</button>
  <button type="button" class="btn btn-success">Success</button>
  <button type="button" class="btn btn-info">Info</button>
  <button type="button" class="btn btn-warning">Warning</button>
  <button type="button" class="btn btn-danger">Danger</button>
  <button type="button" class="btn btn-link">Link</button>
</div>


</body>
</html>

survey_app/templates/survey_app/submit.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Survey App</title>
</head>
<body>
<h3>Thank you for submitting!</h3>
</body>
</html>